# Generated by Django 4.0.4 on 2022-06-15 17:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категорий',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='назваие продукта')),
                ('descriptin', models.TextField(verbose_name='описание')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='цена')),
                ('poster', models.ImageField(upload_to='product/', verbose_name='изоброжение')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='день випуска')),
                ('url', models.SlugField(max_length=130, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='черновик')),
            ],
            options={
                'verbose_name': 'прдукт',
                'verbose_name_plural': 'прдукти',
            },
        ),
        migrations.CreateModel(
            name='Rating_star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0, verbose_name='значение')),
            ],
            options={
                'verbose_name': 'звезда рейтинга',
                'verbose_name_plural': 'звезди рейтинга',
            },
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('age', models.PositiveSmallIntegerField(default=18, verbose_name='возраст')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(upload_to='salesman/', verbose_name='Изоброжение')),
            ],
            options={
                'verbose_name': 'продовец',
                'verbose_name_plural': 'Продовци',
            },
        ),
        migrations.CreateModel(
            name='Shop_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='имя')),
                ('description', models.TextField(verbose_name='описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'название магазина',
                'verbose_name_plural': 'название магазинов',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('text', models.TextField(max_length=5000, verbose_name='сообщение')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.reviews', verbose_name='родитель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'Отзив',
                'verbose_name_plural': 'Отзиви',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='фильм')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rating_star', verbose_name='зведа')),
            ],
            options={
                'verbose_name': 'рейтинг',
                'verbose_name_plural': 'рейтинги',
            },
        ),
        migrations.CreateModel(
            name='product_Shorts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('image', models.ImageField(upload_to='product_shorts/', verbose_name='изоброжение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'кадри продукта',
                'verbose_name_plural': 'кадри продукта',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Shop_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.shop_name', verbose_name='название магазина'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='main.category', verbose_name='категорий'),
        ),
        migrations.AddField(
            model_name='product',
            name='salesman',
            field=models.ManyToManyField(related_name='salesman', to='main.salesman', verbose_name='продовец'),
        ),
    ]
