# Generated by Django 4.0.4 on 2022-06-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_price_alter_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='номер телефона'),
            preserve_default=False,
        ),
    ]
