# Generated by Django 4.0.4 on 2022-06-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_product_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.PositiveSmallIntegerField(default=1, help_text='указивать от 1 до 12', verbose_name='месяц випуска'),
        ),
    ]
