# Generated by Django 4.0.4 on 2022-06-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_rating_star_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptin_en',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='descriptin_ru',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='назваие продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='назваие продукта'),
        ),
        migrations.AddField(
            model_name='product_shorts',
            name='description_en',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='product_shorts',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='product_shorts',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='product_shorts',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='description_en',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='имя'),
        ),
    ]
