# Generated by Django 4.0.4 on 2022-06-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_category_description_en_category_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='data',
        ),
    ]
